#!/bin/sh

message_file=$1
subject=$(sed -n '1p' "$message_file")

if ! printf '%s\n' "$subject" | grep -Eq '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([[:alnum:]_.-]+\))?(!)?: .+'; then
    printf '%s\n' "warning: commit subject is not Conventional Commits compliant: $subject" >&2
fi

exit 0

